name: ganakys_server
description: Ganakys Academy Backend Server
version: 1.0.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod: 2.9.2
  crypto: ^3.0.6
  http: ^1.2.0
  dart_jsonwebtoken: ^2.14.1
  bcrypt: ^1.1.3
  otp: ^3.1.4
  pdf: ^3.11.1
  intl: ^0.19.0
  mime: ^1.0.6
  uuid: ^4.5.1

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  test: '^1.24.2'
  serverpod_test: 2.9.2
