apiServer:
  port: 8080
  publicHost: academy.ganakys.com
  publicPort: 443
  publicScheme: https

insightsServer:
  port: 8081
  publicHost: academy.ganakys.com
  publicPort: 443
  publicScheme: https

webServer:
  port: 8082
  publicHost: academy.ganakys.com
  publicPort: 443
  publicScheme: https

database:
  host: postgres
  port: 5432
  name: ganakys
  user: ganakys

redis:
  enabled: true
  host: redis
  port: 6379

maxRequestSize: 52428800

sessionLogs:
  consoleEnabled: true
  consoleLogFormat: json

futureCallExecutionEnabled: true
