name: ganakys_flutter
description: Ganakys Academy - Online Learning Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  serverpod_flutter: 2.9.2
  ganakys_client:
    path: ../ganakys_client

  # State Management
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^14.6.2

  # UI
  cupertino_icons: ^1.0.5
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  # Video
  chewie: ^1.8.5
  video_player: ^2.9.2

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.3
  flutter_markdown: ^0.7.4
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_lints: '>=3.0.0 <7.0.0'
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
